In [30]:
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity
df = pd.read_csv(r"top10s.csv", encoding="ISO-8859-1")
df

index                                              title  \
0        1                                   Hey, Soul Sister   
1        2                               Love The Way You Lie   
2        3                                            TiK ToK   
3        4                                        Bad Romance   
4        5                               Just the Way You Are   
..     ...                                                ...   
598    599                Find U Again (feat. Camila Cabello)   
599    600      Cross Me (feat. Chance the Rapper & PnB Rock)   
600    601  No Brainer (feat. Justin Bieber, Chance the Ra...   
601    602    Nothing Breaks Like a Heart (feat. Miley Cyrus)   
602    603                                   Kills You Slowly   

               artist        top genre  year  bpm  nrgy  dnce  dB  live  val  \
0               Train       neo mellow  2010   97    89    67  -4     8   80   
1              Eminem  detroit hip hop  2010   87    93    75  -5    52   64   
2               Kesha        dance pop  2010  120    84    76  -3    29   71   
3           Lady Gaga        dance pop  2010  119    92    70  -4     8   71   
4          Bruno Mars              pop  2010  109    84    64  -5     9   43   
..                ...              ...   ...  ...   ...   ...  ..   ...  ...   
598       Mark Ronson        dance pop  2019  104    66    61  -7    20   16   
599        Ed Sheeran              pop  2019   95    79    75  -6     7   61   
600         DJ Khaled        dance pop  2019  136    76    53  -5     9   65   
601       Mark Ronson        dance pop  2019  114    79    60  -6    42   24   
602  The Chainsmokers       electropop  2019  150    44    70  -9    13   23   

     dur  acous  spch  pop  
0    217     19     4   83  
1    263     24    23   82  
2    200     10    14   80  
3    295      0     4   79  
4    221      2     4   78  
..   ...    ...   ...  ...  
598  176      1     3   75  
599  206     21    12   75  
600  260      7    34   70  
601  217      1     7   69  
602  213      6     6   67  

[603 rows x 15 columns]

In [31]:
features = ['title', 'artist', 'top genre']
for feature in features:
    df[feature] = df[feature].fillna('')

In [32]:
def combined_features(row):
    return row['title']+" "+row['artist']+" "+row['top genre']
df["combined_features"] = df.apply(combined_features, axis =1)
df

index                                              title  \
0        1                                   Hey, Soul Sister   
1        2                               Love The Way You Lie   
2        3                                            TiK ToK   
3        4                                        Bad Romance   
4        5                               Just the Way You Are   
..     ...                                                ...   
598    599                Find U Again (feat. Camila Cabello)   
599    600      Cross Me (feat. Chance the Rapper & PnB Rock)   
600    601  No Brainer (feat. Justin Bieber, Chance the Ra...   
601    602    Nothing Breaks Like a Heart (feat. Miley Cyrus)   
602    603                                   Kills You Slowly   

               artist        top genre  year  bpm  nrgy  dnce  dB  live  val  \
0               Train       neo mellow  2010   97    89    67  -4     8   80   
1              Eminem  detroit hip hop  2010   87    93    75  -5    52   64   
2               Kesha        dance pop  2010  120    84    76  -3    29   71   
3           Lady Gaga        dance pop  2010  119    92    70  -4     8   71   
4          Bruno Mars              pop  2010  109    84    64  -5     9   43   
..                ...              ...   ...  ...   ...   ...  ..   ...  ...   
598       Mark Ronson        dance pop  2019  104    66    61  -7    20   16   
599        Ed Sheeran              pop  2019   95    79    75  -6     7   61   
600         DJ Khaled        dance pop  2019  136    76    53  -5     9   65   
601       Mark Ronson        dance pop  2019  114    79    60  -6    42   24   
602  The Chainsmokers       electropop  2019  150    44    70  -9    13   23   

     dur  acous  spch  pop                                  combined_features  
0    217     19     4   83                  Hey, Soul Sister Train neo mellow  
1    263     24    23   82        Love The Way You Lie Eminem detroit hip hop  
2    200     10    14   80                            TiK ToK Kesha dance pop  
3    295      0     4   79                    Bad Romance Lady Gaga dance pop  
4    221      2     4   78                Just the Way You Are Bruno Mars pop  
..   ...    ...   ...  ...                                                ...  
598  176      1     3   75  Find U Again (feat. Camila Cabello) Mark Ronso...  
599  206     21    12   75  Cross Me (feat. Chance the Rapper & PnB Rock) ...  
600  260      7    34   70  No Brainer (feat. Justin Bieber, Chance the Ra...  
601  217      1     7   69  Nothing Breaks Like a Heart (feat. Miley Cyrus...  
602  213      6     6   67       Kills You Slowly The Chainsmokers electropop  

[603 rows x 16 columns]

In [33]:
cv = CountVectorizer()
count_matrix = cv.fit_transform(df["combined_features"])
print("Count Matrix:", count_matrix.toarray())

Count Matrix: [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [34]:
cosine_sim = cosine_similarity(count_matrix)
cosine_sim

array([[1.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 1.        , 0.        , ..., 0.09245003, 0.        ,
        0.27216553],
       [0.        , 0.        , 1.        , ..., 0.24806947, 0.26967994,
        0.        ],
       ...,
       [0.        , 0.09245003, 0.24806947, ..., 1.        , 0.2508726 ,
        0.1132277 ],
       [0.        , 0.        , 0.26967994, ..., 0.2508726 , 1.        ,
        0.        ],
       [0.        , 0.27216553, 0.        , ..., 0.1132277 , 0.        ,
        1.        ]])

In [35]:
track_user_likes = "Hey, Soul Sister"
def get_index_from_title(title):
    return df[df.title == title]["index"].values[0]
track_index = get_index_from_title(track_user_likes)
similar_tracks = list(enumerate(cosine_sim[track_index]))
sorted_similar_tracks = sorted(similar_tracks, key=lambda x:x[1], reverse=True)

In [37]:
def get_title_from_index(index):
    return df[df.index == index]["title"].values[0]
i=0
for movie in sorted_similar_tracks:
    print(get_title_from_index(movie[0]))
    i=i+1
    if i>15:
        break

detroit hip hop
detroit hip hop
hip hop
dance pop
pop
pop
hip hop
dance pop
hip hop
atl hip hop
dance pop
atl hip hop
australian hip hop
canadian hip hop
hip hop
electropop
